context:
  version: "0.24.2"

package:
  name: iwe
  version: ${{ version }}

source:
  url: https://github.com/iwe-org/iwe/archive/refs/tags/iwe-v${{ version }}.tar.gz
  sha256: ea8fd57950a99a535306528cbbca1ba04e7f74090dba823518f818a7078d9e5c

build:
  number: 0
  script:
    env:
      CARGO_PROFILE_RELEASE_LTO: fat
      CARGO_PROFILE_RELEASE_STRIP: symbols
    interpreter: nu
    content:
      - let prefix = $env.LIBRARY_PREFIX? | default $env.PREFIX
      # build main app and generate license data
      - cargo auditable install --path=crates/iwe  --root=($prefix) --no-track --locked --bins
      - cargo auditable install --path=crates/iwec --root=($prefix) --no-track --locked --bins
      - cargo auditable install --path=crates/iwes --root=($prefix) --no-track --locked --bins
      - cargo-bundle-licenses --format=yaml --output=THIRDPARTY.yml
      # generate shell completions
      - if: build_platform == host_platform
        then:
          - mkdir ($prefix)/share/bash-completion/completions ($prefix)/share/fish/vendor_completions.d ($prefix)/share/zsh/site-functions
          - let bin = ($prefix)/bin/iwe
          - ^$bin completions bash | save ($prefix)/share/bash-completion/completions/iwe
          - ^$bin completions fish | save ($prefix)/share/fish/vendor_completions.d/iwe.fish
          - ^$bin completions zsh  | save ($prefix)/share/zsh/site-functions/_iwe

requirements:
  build:
    - ${{ stdlib('c') }}
    - ${{ compiler('c') }}
    - ${{ compiler('rust') }}
    - cargo-auditable
    - cargo-bundle-licenses
    - nushell

tests:
  - script:
      - iwe --help
      - iwe --version
  - package_contents:
      bin:
        - iwe
        - iwec
        - iwes
      files:
        - if: unix and build_platform == host_platform
          then:
            - share/bash-completion/completions/iwe
            - share/fish/vendor_completions.d/iwe.fish
            - share/zsh/site-functions/_iwe
        - if: win and build_platform == host_platform
          then:
            - Library/share/bash-completion/completions/iwe
            - Library/share/fish/vendor_completions.d/iwe.fish
            - Library/share/zsh/site-functions/_iwe
      strict: true

about:
  summary: IWE – Markdown memory system for you and your AI Agents
  description: |
    IWE is a knowledge graph system that serves as a "second brain" for humans
    and AI agents. It organizes notes hierarchically and makes them accessible
    through CLI tools and LSP for editor integration (VS Code, Neovim, Zed,
    Helix etc.).
  license: Apache-2.0
  license_file:
    - LICENSE-APACHE
    - THIRDPARTY.yml
  homepage: https://iwe.org
  documentation: https://iwe.md/docs/
  repository: https://github.com/iwe-org/iwe

extra:
  recipe-maintainers:
    - salim-b
